---

- name: Install Deployment Packages
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present
  with_items:
    - aptitude
    - build-essential
    - git
    - ntp
    - openssh-server
    - python-dev
    - sudo    

- name: Install Openstack Ansible
  git:
    repo: 'https://git.openstack.org/openstack/openstack-ansible'
    dest: /opt/openstack-ansible
    version: 16.0.5
